name: balls-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  #Science stack
  - numpy
  - matplotlib
  - imageio 
  - cma
  - scipy
#PyTorchstack
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
    - -e . #install my library
    - pywebview
    - streamline
