name: balls-env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pytorch
  - pytorch-cuda=11.8
  - imageio 
  - cma
  - scipy
  - pip:
    - jax
    - jaxlib
    - torch-geometric
    - stable-baselines3
    - -e . #install my library
